const ICON_FILES = {
  '👍': 'thumbsup',
  '👎': 'thumbsdown',
  '😂': 'laugh',
  '😮': 'surprised',
  '😢': 'cry',
  '🔥': 'fire',
  '🤝': 'handshake',
  '🖕': 'middlefinger',
  '🤡': 'clown',
  '💤': 'zzz',
  '🌹': 'rose',
  '🍺': 'beer',
  '👑': 'crown',
  '🎉': 'party',
  '💎': 'gem',
  '🍕': 'pizza',
  '🚀': 'rocket',
  '🐷': 'pig',
  '🎁': 'giftbox',
  '😱': 'shocked',
  '🤔': 'thinking',
  '😎': 'cool',
  '🙄': 'eyeroll',
  '👏': 'clap',
  '🙏': 'pray',
  '💪': 'flex',
  '🤦': 'facepalm',
  '😏': 'smirk',
  '🥳': 'partyface',
  '🍾': 'champagne',
  '🏆': 'trophy',
  '💰': 'moneybag',
  '🎂': 'cake',
  '🍫': 'chocolate',
  '🧧': 'redenvelope',
  '🌟': 'star',
  '🍷': 'wine',
  '🦄': 'unicorn',
  '🎈': 'balloon',
  '🍀': 'clover',
};

export function emojiIconSrc(char) {
  const name = ICON_FILES[char];
  return name ? `/icons/emoji/${name}.svg` : null;
}
