// Interface copy only. Player names, chat messages and free-form profile text stay as entered.
const EN = {
  '创建房间': 'Create Room', '加入房间': 'Join Room', '设置': 'Settings', '好友': 'Friends',
  '藏品': 'Collection', '商店': 'Shop', '活动': 'Events', '主菜单': 'Main Menu',
  '可加入的房间': 'Available Rooms', '刷新中': 'Refreshing', '刷新': 'Refresh',
  '暂时没有公开的房间': 'No public rooms yet', '房间号': 'Room Code', '进入': 'Enter',
  '返回': 'Back', '我的身份': 'My Identity', '昵称': 'Nickname', '确认': 'Confirm',
  '完成': 'Done', '未填写昵称': 'No nickname', '你的名字': 'Your name',
  '例如 A7B2C': 'e.g. A7B2C', '画面': 'Display', '声音': 'Audio',
  '游戏语言': 'Game Language', '界面缩放': 'UI Scale', '动画效果': 'Motion',
  '音效': 'Sound Effects', '音效音量': 'Sound Volume', '语音播报': 'Voice Announcements',
  '播报语言': 'Announcement Language', '播报音量': 'Announcement Volume',
  '播报角色': 'Voice Character', '试听播报': 'Preview Voice', '中文': 'Chinese',
  '日语 · VOICEVOX': 'Japanese · VOICEVOX', '跟随系统': 'Follow System',
  '开启': 'On', '关闭': 'Off', '开': 'On', '关': 'Off',
  '紧凑': 'Compact', '标准': 'Standard', '大': 'Large', '特大': 'Extra Large',
  '邀请好友': 'Invite Friends', '房间内容': 'Room Contents', '同桌玩家': 'Players at Table',
  '牌局规则': 'Game Rules', '初始筹码': 'Starting Chips', '每人最多': 'Max per player',
  '盲注': 'Blinds', '小盲': 'Small Blind', '大盲': 'Big Blind',
  '小盲 / 大盲': 'Small / Big Blind', '游戏模式': 'Game Mode',
  '经典牌局': 'Classic Poker', '千术模式': 'Trick Mode', '千术图鉴': 'Trick Catalog',
  '标准德州，不限局数': 'Standard Hold’em, unlimited hands', '共 16 局': '16 hands',
  '局数': 'Hands', '不限': 'Unlimited', '不限次数': 'Unlimited Raises',
  '每轮限一次': 'One Raise per Round', '自定义': 'Custom', '加注规则': 'Raise Rules',
  '单轮下注上限': 'Bet Limit per Round', '整局下注上限': 'Bet Limit per Hand',
  '房主': 'Host', '离线': 'Offline', '在线': 'Online', '你': 'You',
  '房间战绩': 'Room Results', '开始游戏': 'Start Game', '至少需要 2 名玩家': 'At least 2 players required',
  '等待房主开始': 'Waiting for host', '离开房间': 'Leave Room', '+ 机器人': '+ Bot',
  '聊天': 'Chat', '还没有人说话': 'No messages yet', '表情': 'Emoji',
  '快捷': 'Quick Chat', '说点什么…': 'Say something…', '聊天内容': 'Chat message',
  '发送': 'Send', '收起聊天': 'Hide Chat', '送给': 'sent to',
  '快点吧': 'Hurry up!', '好牌！': 'Nice hand!', '稳住别慌': 'Stay calm',
  '我全下了': 'I’m all in', '运气不错': 'Lucky me', '再来一局': 'One more game',
  '轮到你行动': 'Your Turn', '筹码': 'Chips', '弃牌': 'Fold', '过牌': 'Check',
  '跟注': 'Call', '加注': 'Raise', '全下': 'All In', '（全下）': ' (All In)',
  '加注到': 'Raise to', '需投入': 'Cost', '快捷选择加注金额': 'Quick Raise Amounts',
  '最小': 'Min', '最大': 'Max', '重置': 'Reset', '选择加注金额': 'Choose Raise Amount',
  '发牌中': 'Dealing', '翻牌前': 'Preflop', '翻牌': 'Flop', '转牌': 'Turn',
  '河牌': 'River', '摊牌': 'Showdown', '牌局中': 'Playing', '牌桌工具': 'Table Tools',
  '牌谱': 'Hand Rankings', '返回大厅': 'Return to Lobby', '底池': 'Pot',
  '语音': 'Voice', '牌桌语音': 'Table Voice', '加入语音': 'Join Voice',
  '退出语音': 'Leave Voice', '麦克风已静音': 'Microphone Muted',
  '语音已开启': 'Voice On', '尚未加入': 'Not Joined', '正在连接…': 'Connecting…',
  '连接中': 'Connecting', '未连接': 'Disconnected', '已连接': 'Connected',
  '等待其他玩家加入': 'Waiting for others', '暂无玩家加入语音': 'Nobody in voice chat',
  '在语音频道中': 'In voice chat', '已为你静音': 'Muted for you',
  '连接中断，可退出后重试': 'Connection lost; leave and retry',
  '开启麦克风': 'Enable microphone', '静音麦克风': 'Mute microphone',
  '取消静音': 'Unmute', '静音': 'Mute', '输入音量': 'Input Volume', '音量': 'Volume',
  '自己的麦克风输入音量': 'Your microphone input volume',
  '正在开启麦克风…': 'Enabling microphone…',
  '最终结算': 'Final Results', '本局结算': 'Hand Results', '展开': 'Expand', '收起': 'Collapse',
  '其他玩家弃牌': 'Other players folded', '分得': 'Won', '本局净': 'Net',
  '赢': 'Win', '输': 'Loss', '查看底牌': 'View Hole Cards', '已查看': 'Viewed',
  '全桌千术公开': 'All Tricks Revealed', '补筹码': 'Rebuy', '剩余': 'Remaining',
  '等待房主补筹码': 'Waiting for host to rebuy', '你已出局': 'You are out',
  '已确认，等待其他玩家': 'Ready; waiting for others', '继续下一局': 'Continue',
  '本局已结束，下一局自动入座': 'This hand is over; seated next hand',
  '牌局结束，45 秒后返回大厅': 'Game over; returning to lobby in 45 seconds',
  '45 秒后返回大厅': 'Returning to lobby in 45 seconds',
  '千术': 'Trick', '出千': 'Use Trick', '我的千术': 'My Tricks',
  '普通': 'Common', '罕见': 'Rare', '史诗': 'Epic', '传说': 'Legendary',
  '全部': 'All', '被动': 'Passive', '行动': 'Action', '情报': 'Intel',
  '被动（可操作）': 'Passive (Interactive)', '次数': 'Uses', '触发': 'Trigger',
  '条件': 'Condition', '使用次数': 'Uses', '使用条件': 'Use Condition',
  '生效时机': 'Trigger', '自动生效': 'Automatic', '可以使用': 'Available',
  '点击后在牌桌上操作': 'Click, then choose cards on the table',
  '仅轮到你行动时可用': 'Only available on your turn',
  '仅翻牌前自己的行动回合可选底牌': 'Choose hole cards on your preflop turn',
  '本局还没有可换入的已弃底牌': 'No discarded hole cards available yet',
  '可抽取筹码不足 10': 'Fewer than 10 chips available to take',
  '当前不满足使用条件或次数已用完': 'Conditions unmet or no uses left',
  '猜河牌花色': 'Guess River Suit', '指定已翻出的公共牌': 'Choose Revealed Community Card',
  '锁定的公共牌': 'Locked Community Card', '红桃': 'Hearts', '方块': 'Diamonds',
  '梅花': 'Clubs', '黑桃': 'Spades', '未翻出': 'Not Revealed',
  '本局情报': 'This Hand’s Intel', '选千术': 'Choose Trick', '已完成': 'Complete',
  '待开启': 'Locked', '补选千术': 'Catch-up Trick Pick', '秒后自动选择': 'seconds until auto-pick',
  '已选择': 'Selected', '已持有': 'Owned', '选择': 'Select',
  '已无刷新次数': 'No refreshes left', '等待本阶段选术结束': 'Waiting for trick picks',
  '选中后额外赠送一项随机普通千术': 'Also gain a random common trick',
  '搜索千术': 'Search Tricks', '搜索名称或效果': 'Search names or effects',
  '载入图鉴…': 'Loading catalog…', '图鉴暂时无法载入': 'Catalog unavailable',
  '没有找到符合条件的千术': 'No matching tricks', '按品阶筛选': 'Filter by rarity',
  '关闭千术图鉴': 'Close Trick Catalog', '关闭千术手册': 'Close My Tricks',
  '取消': 'Cancel', '确认选择': 'Confirm Selection', '已选': 'Selected',
  '现有底牌': 'Current Hole Cards', '备用牌': 'Spare Card',
  '亮底牌': 'Reveal Hole Cards', '全桌可见': 'Visible to all',
  '已被踢出': 'Removed', '下一局加入': 'Join next hand',
  '经典': 'Classic', '插画': 'Illustrated', '高对比': 'High Contrast',
  '金线': 'Gold Lines', '朱红': 'Vermilion', '青玉': 'Jade', '黑银': 'Black & Silver',
  '暖橙': 'Warm Orange', '钴蓝': 'Cobalt Blue', '樱花': 'Sakura',
  '山景': 'Mountain', '霓虹': 'Neon', '黑金': 'Black & Gold',
  '浪纹': 'Waves', '青瓷': 'Celadon', '星空': 'Starfield',
  '虎纹': 'Tiger', '玫瑰': 'Rose', '冰蓝': 'Ice Blue',
  '竹纹': 'Bamboo', '像素': 'Pixel', '海图': 'Sea Chart', '漫画': 'Comic',
  '深蓝': 'Deep Blue', '暖红': 'Warm Red', '深紫': 'Deep Purple',
  '棕色皮革': 'Brown Leather', '青绿': 'Teal', '黑色': 'Black',
  '极光': 'Aurora', '酒红': 'Wine Red', '月面': 'Moon',
  '竹林': 'Bamboo Grove', '熔岩': 'Lava', '冰川': 'Glacier',
  '沙漠': 'Desert', '水墨': 'Ink Wash', '深海': 'Deep Sea',
  '石柱': 'Columns', '枯山水': 'Zen Garden', '光网': 'Light Grid',
  '月白': 'Ivory', '夜樱': 'Night Sakura', '学院侦探': 'Academy Detective',
  '和风术士': 'Japanese Diviner', '赛博骇客': 'Cyber Hacker',
  '学级裁判': 'Class Trial', '巫女': 'Shrine Maiden',
  '暗黑哥特': 'Dark Gothic', '地雷系': 'Jirai Kei',
  '素色': 'Plain', '鎏金': 'Gilded', '翠玉': 'Jade',
  '青海波': 'Blue Waves', '星云': 'Nebula', '烈焰': 'Flame',
  '霜雪': 'Frost', '皇家': 'Royal', '赤龙': 'Red Dragon',
  '皇家同花顺': 'Royal Flush', '同花顺': 'Straight Flush', '四条': 'Four of a Kind',
  '葫芦': 'Full House', '同花': 'Flush', '顺子': 'Straight',
  '三条': 'Three of a Kind', '两对': 'Two Pair', '一对': 'Pair', '高牌': 'High Card',
};

Object.assign(EN, {
  '暗纹·浅痕': 'Shadow Mark · Trace', '暗纹·群影': 'Shadow Mark · Many',
  '暗纹·锁痕': 'Shadow Mark · Lock', '窥底·识点': 'Hole Peek · Rank',
  '窥底·真相': 'Hole Peek · Truth', '窥底·透视': 'Hole Peek · X-Ray',
  '天眼': 'All-Seeing Eye', '对子警报': 'Pair Alert', '对子点名': 'Pair Roll Call',
  '读秒·缓时': 'Extra Time', '读秒·夺时': 'Time Thief',
  '防窥·遮影': 'Peek Shield', '防窥·封牌': 'Card Lock',
  '换底·五选二': 'Five-Card Swap', '定河山': 'Control Turn & River',
  '乾坤错位': 'Hole-Card Exchange', '抽筹·探囊': 'Pot Pickpocket',
  '抽筹·顺手': 'Neighbor Pickpocket', '抽筹·截流': 'Pot Drain',
  '留底·五留二': 'Keep Two of Five', '留底·七留二': 'Keep Two of Seven',
  '留底·八留四': 'Keep Four of Eight', '留底·釜底抽薪': 'Deep Reserve',
  '废牌·拾遗': 'Discard Recovery', '废牌·寻迹': 'Discard Trail',
  '废牌·尽收': 'Discard Exchange', '数花': 'Suit Count',
  '赠筹·买断': 'Paid Fold', '同花顺识别': 'Suit or Run',
  '亮牌换筹': 'Reveal for Chips', '盲盒': 'Blind Box',
  '第六感': 'Sixth Sense', '我要验牌': 'Board Audit',
  '破局录': 'Trick Trace', '起底': 'Expose Loadout',
  '河牌公报': 'River Report', '胜负直觉': 'Winning Instinct',
  '天命易手': 'Fate Swap', '高张试探': 'High-Card Probe',
  '红潮': 'Red Tide', '牌兆·王牌气息': 'Ace Signal',
  '牌兆·花牌点名': 'Face-Card Signal', '听色': 'Color Sense',
  '望高': 'High-Card Glimpse', '自照': 'Future Self',
  '盲注回声': 'Blind Echo', '无声手法': 'Silent Hands',
  '押色': 'Suit Bet', '底张': 'Bottom Deal', '探术': 'Trick Probe',
  '算牌': 'Card Count', '牌型嗅觉': 'Hand Sense', '天窗': 'Next-Card Peek',
  '抬眼': 'Table Leader', '偷师': 'Steal a Trick', '改花': 'Suit Shift',
  '风向': 'Next Suit', '几分胜算': 'Strength Count', '倒序': 'Reverse Board',
  '偷梁入手': 'Steal a Hole Card', '千术点将': 'Reveal All Tricks',
  '地底之下': 'Below Ground', '无冤无仇': 'Random Replacement',
  '特异功能·掩目': 'Blindfold', '地面之中': 'At Ground Level',
  '探囊取物': 'Steal Future Board', '捉千': 'Catch a Cheat',
  '天空之下': 'Under the Sky', '混沌之子': 'Child of Chaos',
  '左邻右舍': 'Neighbors', '功力耗尽': 'Trick Shutdown',
  '千术反转': 'Trick Reflection', '天空之外': 'Beyond the Sky',
  '云中探花手': 'Ace-King from the Clouds',
  '特异功能·精神错乱': 'Mind Scramble',
  '一张ACE': 'One Ace', '一张King': 'One King', '一张Queen': 'One Queen',
  '千术冥想': 'Trick Meditation', '千术多多': 'More Tricks',
  '千术抵抗': 'Trick Resistance', '纯粹主义者': 'Purist',
  '雨露均沾': 'Shared Rain', '摆份·不需要公牌': 'Bluff · No Board Needed',
  '摆份·跟你盲开': 'Bluff · Blind Together', '摆份·无需看牌': 'Bluff · No Look',
  '特异功能·意念闭塞': 'Mental Block', '给我擦皮鞋': 'Shine My Shoes',
  '牌仙子': 'Card Fairy', '你真的看清楚了吗': 'Did You Really See?',
  '自我暗示': 'Self-Suggestion', '不动如山': 'Immovable',
  '管中窥豹': 'Guess the Hole Cards', '终极替换': 'Ultimate Swap',
  '禁止成对': 'No Pairs', '写轮眼': 'Copy Eye',
  '阴间·阴阳眼': 'Underworld · Yin-Yang Eye',
  '阴间·鬼眼': 'Underworld · Ghost Eye', '阴间·佛眼': 'Underworld · Buddha Eye',
  '搅屎棍': 'False Intel', '黑潮': 'Black Tide',
  '登神阶梯I': 'Ascension Ladder I', '登神阶梯II': 'Ascension Ladder II',
  '登神阶梯III': 'Ascension Ladder III', '登神': 'Ascended',
  '以量取胜': 'Strength in Numbers', '终极抵抗反转': 'Ultimate Counter',
  '定江山': 'Control the Flop', '运筹帷幄': 'Strategic Reserve',
});

Object.assign(EN, {
  '开局查看一名随机对手两张底牌各自的红黑。': 'At the start of each hand, see the color of each hole card held by one random opponent.',
  '查看所有对手起始底牌的红黑；之后换牌不会更新这份情报。': 'See the starting colors of every opponent’s hole cards. Later swaps do not update this information.',
  '查看每名对手一张底牌的红黑、另一张的具体花色，以及第一张翻牌的花色。': 'See the color of one hole card and the exact suit of the other for every opponent, plus the suit of the first flop card.',
  '查看指定对手一张随机底牌的点数。': 'See the rank of one random hole card held by a chosen opponent.',
  '完整查看指定对手的一张指定底牌。': 'See one chosen hole card held by a chosen opponent.',
  '完整查看指定对手的两张底牌。': 'See both hole cards held by a chosen opponent.',
  '完整查看所有未受防窥保护的对手底牌。': 'See all hole cards held by opponents without peek protection.',
  '得知有几名对手拿到口袋对子。': 'Learn how many opponents were dealt a pocket pair.',
  '得知谁拿到口袋对子，以及对子点数是否不大于 8。': 'Learn which opponents have a pocket pair and whether its rank is 8 or lower.',
  '你的每次行动时间增加 10 秒。': 'Gain 10 seconds for each of your turns.',
  '你的每次行动增加 10 秒，其他玩家各减少 15 秒。': 'Gain 10 seconds per turn; each other player loses 15 seconds per turn.',
  '对手无法窥视你的底牌，但仍能用千术转移它们。': 'Opponents cannot peek at your hole cards, but can still move them with tricks.',
  '对手无法窥视或转移你的底牌；正常摊牌不受影响。': 'Opponents cannot peek at or move your hole cards. Normal showdown is unaffected.',
  '从当前两张底牌和三张随机牌中挑选两张，作为新的底牌。': 'Choose two new hole cards from your current two and three random cards.',
  '从十张随机牌中按顺序指定转牌和河牌。': 'Choose the turn and river, in order, from ten random cards.',
  '与指定对手交换双方各一张指定底牌，或直接交换两张底牌。': 'Exchange one chosen hole card with a chosen opponent, or exchange both hole cards.',
  '底池至少有五个小盲时，结算前随机抽走一至五个小盲。': 'If the pot holds at least five small blinds, take one to five small blinds before settlement.',
  '随机从左邻或右邻取走其筹码的四分之一，向下取整到十。': 'Take a quarter of a random left or right neighbor’s chips, rounded down to a multiple of ten.',
  '从底池抽走一半筹码，向下取整到十的倍数。': 'Take half the pot, rounded down to a multiple of ten.',
  '每局抽五张牌：从前三张挑两张作底牌；其余两张只供你查看，不再入局。': 'Each hand, draw five cards. Choose two of the first three as hole cards; view the other two, then remove them.',
  '每局抽七张牌：从前三张挑两张作底牌；其余四张只供你查看，不再入局。': 'Each hand, draw seven cards. Choose two of the first three as hole cards; view the other four, then remove them.',
  '每局抽八张牌：从前四张挑两张作底牌；其余四张只供你查看，不再入局。': 'Each hand, draw eight cards. Choose two of the first four as hole cards; view the other four, then remove them.',
  '每局抽十张牌：翻前从前五张挑两张作底牌；河牌时可用后五张中的一张替换底牌。': 'Each hand, draw ten cards. Before the flop, choose two of the first five as hole cards; on the river, you may swap in one of the last five.',
  '私下查看本局首位弃牌者的两张底牌。': 'Privately see both hole cards of the first player to fold this hand.',
  '自动私下查看本局所有弃牌者的底牌。': 'Privately see the hole cards of every player who folds this hand.',
  '全桌公开弃牌者的底牌；你可拿其中一张与自己的一张底牌交换。': 'Reveal folded players’ hole cards to the table; you may exchange one with one of yours.',
  '查看未使用牌中四种花色各剩多少张。': 'See how many unused cards remain in each suit.',
  '支付底池四分之一给后位对手；等他行动时只能弃牌，但仍可使用千术。': 'Pay a quarter of the pot to a later-position opponent. On their next turn they can only fold, but may still use tricks.',
  '判断指定对手的两张底牌是否同花或点数相连；A2、AK 也算相连。': 'Learn whether a chosen opponent’s hole cards share a suit or have consecutive ranks; A-2 and A-K count as consecutive.',
  '公开自己的底牌，并从每名筹码足够的对手手中收取一个大盲。': 'Reveal your hole cards and collect one big blind from each opponent with enough chips.',
  '私下查看三张随机未使用牌。': 'Privately see three random unused cards.',
  '首次被对手窥牌或换牌时，得知是谁及其使用的千术。': 'The first time an opponent peeks at or swaps your cards, learn who did it and which trick they used.',
  '查出本局用千术换过公牌的对手，并让尚未全下者立即弃牌。': 'Identify opponents who changed community cards with tricks this hand; those not all in fold immediately.',
  '每名对手首次使用主动千术时，私下得知其千术名称。': 'Privately learn the name of each opponent’s first active trick.',
  '私下查看指定对手持有的全部千术，以及两张底牌的点数。': 'Privately see all tricks held by a chosen opponent and the ranks of both their hole cards.',
  '私下得知全桌最高牌型，并向全桌公告其是否达到两对。': 'Privately learn the table’s highest hand category; announce to everyone whether it is at least two pair.',
  '比较你与指定对手当前的牌力，得知领先、落后或持平。': 'Compare your current hand strength with a chosen opponent: ahead, behind, or tied.',
  '与当前牌力最强的一名随机对手交换两张底牌。': 'Exchange both hole cards with a random opponent among those currently holding the strongest hand.',
  '判断指定对手是否持有 J、Q、K 或 A。': 'Learn whether a chosen opponent holds a J, Q, K, or A.',
  '得知其他玩家底牌中共有几张红牌。': 'Learn how many red hole cards the other players hold in total.',
  '得知是否有对手握有 A。': 'Learn whether any opponent holds an ace.',
  '得知有几名对手握有 J、Q 或 K。': 'Learn how many opponents hold a J, Q, or K.',
  '私下得知转牌和河牌各自的红黑。': 'Privately learn the colors of the turn and river cards.',
  '判断下一张公共牌的点数是否至少为 10。': 'Learn whether the next community card has a rank of at least 10.',
  '判断下一张公共牌能否提升你当前的牌型等级。': 'Learn whether the next community card will improve your hand category.',
  '翻前每有一人的总下注恰好等于一个大盲，翻牌后便从底池取回一个大盲。': 'After the flop, reclaim one big blind from the pot for each player whose total preflop bet was exactly one big blind.',
  '其他玩家不会察觉你使用千术；目标必须收到的效果通知仍会送达。': 'Other players do not notice you using tricks. Required effect notices still reach their targets.',
  '猜中河牌花色后，在本局结算时向每名对手收取一个大盲。': 'Guess the river suit correctly to collect one big blind from each opponent at settlement.',
  '将自己指定的一张底牌换成牌堆最底下的牌。': 'Replace one chosen hole card with the bottom card of the deck.',
  '随机得知指定对手持有的一项千术名称。': 'Learn the name of one random trick held by a chosen opponent.',
  '查看与你底牌同点数的牌，在牌堆中还剩多少张。': 'See how many cards matching your hole-card ranks remain in the deck.',
  '得知指定对手当前的牌型类别。': 'Learn a chosen opponent’s current hand category.',
  '完整查看下一张尚未翻出的公共牌。': 'See the next unrevealed community card.',
  '从最高牌型类别的玩家中随机指出一人；不保证他实际牌力最强。': 'Identify one random player in the highest hand category; they may not have the strongest hand overall.',
  '获得指定对手的一项随机千术，并以它永久替换“偷师”。': 'Gain one random trick from a chosen opponent, permanently replacing Steal a Trick.',
  '将指定底牌换成牌堆中同点数、不同花色的随机牌。': 'Replace a chosen hole card with a random card of the same rank and a different suit from the deck.',
  '私下得知下一张公共牌的花色。': 'Privately learn the suit of the next community card.',
  '得知当前有几名未受防窥保护的对手牌力高于你。': 'Learn how many opponents without peek protection currently have a stronger hand than yours.',
  '预先锁定本局五张公共牌，改按第 5 张至第 1 张的顺序翻出。': 'Lock in this hand’s five community cards, then reveal them in reverse order, fifth to first.',
  '将指定对手的一张底牌，与你的一张随机底牌交换。': 'Exchange one chosen opponent hole card with one random hole card of yours.',
  '私下得知所有对手持有的千术。': 'Privately learn every trick held by every opponent.',
  '选中时额外获得一项随机罕见千术。': 'When picked, also gain one random rare trick.',
  '随机更换一名可换牌玩家的一张底牌；也可能抽中你自己。': 'Randomly replace one hole card of a player eligible for swaps. You may be chosen.',
  '让指定对手看不见前三张翻牌，直到河牌阶段。': 'Hide the three flop cards from a chosen opponent until the river.',
  '选中时额外获得一项随机史诗千术。': 'When picked, also gain one random epic trick.',
  '用自己的两张底牌，与尚未揭晓的转牌和河牌交换。': 'Exchange your two hole cards with the unrevealed turn and river.',
  '从本局用过主动千术的指定对手那里收取二十个大盲；若对方本局没用过，本次落空并消耗次数。': 'Collect 20 big blinds from a chosen opponent who used an active trick this hand. If they did not, the use is spent with no effect.',
  '选中时额外获得两项随机罕见千术。': 'When picked, also gain two random rare tricks.',
  '选中时将自己所有千术（包括此术）随机替换为同样数量的史诗千术（不含自我暗示）。': 'When picked, replace all your tricks, including this one, with the same number of random epic tricks, excluding Self-Suggestion.',
  '交换左邻的右侧底牌和右邻的左侧底牌（跳过已弃牌的玩家）。': 'Exchange the right hole card of the player to your left with the left hole card of the player to your right, skipping folded players.',
  '令指定对手本局无法发动千术。': 'Prevent a chosen opponent from using tricks for the rest of this hand.',
  '被主动千术作用时，临时获得该千术；本局未使用则不消耗次数。': 'When targeted by an active trick, temporarily gain it. If unused this hand, it does not consume a use.',
  '选中时额外获得两项随机史诗千术。': 'When picked, also gain two random epic tricks.',
  '用未使用牌中随机花色的一张 A 和一张 K，替换自己的两张底牌。': 'Replace your hole cards with an unused ace and king of random suits.',
  '立刻把所有其他玩家的两张底牌随机更换。': 'Immediately replace both hole cards of every other player with random cards.',
  '用牌堆里随机一张 A，替换自己点数较小的底牌。': 'Replace your lower-ranked hole card with a random ace from the deck.',
  '用牌堆里随机一张 K，替换自己点数较小的底牌。': 'Replace your lower-ranked hole card with a random king from the deck.',
  '用牌堆里随机一张 Q，替换自己点数较小的底牌。': 'Replace your lower-ranked hole card with a random queen from the deck.',
  '下次选术时，各栏位若抽到普通品质则改抽罕见，抽到罕见则改抽史诗。': 'At your next trick pick, each common offer becomes rare and each rare offer becomes epic.',
  '以后选术时，每个候选栏位都多一次刷新机会。': 'Gain one extra refresh per offer slot for all future trick picks.',
  '每阶段第一次受到换牌千术作用时，抵消整次效果；对方仍消耗使用次数。': 'Negate the first card-swap trick targeting you in each phase; the opponent still spends a use.',
  '初始发牌不会拿到 2 或 7；之后仍可能被千术换入。': 'You will not be dealt a 2 or 7 initially, though tricks may swap one in later.',
  '私下得知所有未受防窥保护玩家较小底牌的点数。': 'Privately learn the lower hole-card rank of every player without peek protection.',
  '本局看不到河牌；若赢牌，从每名弃牌者手中收取十个小盲。': 'You cannot see the river this hand. If you win, collect ten small blinds from each player who folded.',
  '指定一名对手；下一局你们双方都看不到自己的底牌。': 'Choose an opponent. Next hand, neither of you can see your own hole cards.',
  '下一局看不到自己的底牌；若河牌仍未弃且最终为高牌，从赢家收取等于底池的筹码，并向其他玩家各收一个小盲。': 'Next hand, you cannot see your hole cards. If you reach the river and finish with high card, collect chips equal to the pot from the winner and one small blind from each other player.',
  '盖住指定对手的底牌，使其在本局结束前无法查看。': 'Hide a chosen opponent’s hole cards until the end of this hand.',
  '河牌单挑并获胜时，从落败者手中收取本局开局人数个大盲。': 'If you win a heads-up showdown on the river, collect one big blind per player who started this hand from the loser.',
  '以两对或更高牌型赢牌时，额外获得一项随机普通千术；持有数量可超过四项。': 'When you win with two pair or better, gain a random common trick; you may hold more than four.',
  '对手对你取得的千术情报会变假：点数报 2～9，花色和红黑随机，牌型报高牌。': 'Trick intel opponents obtain about you becomes false: ranks appear as 2–9, suits and colors are random, and hand category appears as high card.',
  '选中时失去已持有的全部千术，换取一项随机传说千术。': 'When picked, lose all your tricks and gain one random legendary trick.',
  '你的底牌永久不能被其他玩家的千术替换；每局可在转牌翻出前，锁定转牌或河牌中的一张，任何千术都不能再替换它。': 'Your hole cards can never be replaced by other players’ tricks. Each hand, before the turn, you may lock the turn or river against all trick replacements.',
  '猜中指定对手两张底牌的点数后，令他下次行动只能弃牌。': 'Guess both ranks of a chosen opponent’s hole cards correctly to force them to fold on their next turn.',
  '找出可换的对手底牌中点数最大的两张；只有高于你对应位置的底牌时才逐张交换。': 'Find the two highest-ranked swappable opponent hole cards; swap each only if it outranks your card in the corresponding position.',
  '点选一张已翻出的公共牌，随机换掉其他玩家所有同点数的底牌。': 'Choose a revealed community card; randomly replace every matching-rank hole card held by other players.',
  '从场上每名其他玩家持有的千术中，各随机获得一项。': 'Gain one random trick held by each other player at the table.',
  '开局预知第五张公共牌，但本局看不到第三张公共牌。': 'See the fifth community card at the start of the hand, but cannot see the third card this hand.',
  '发动后的下一局，开局预知转牌和河牌，但看不到前三张公共牌。': 'Next hand after use, see the turn and river at the start but cannot see the three flop cards.',
  '发动后的下一局，开局预知前三张公共牌，但看不到转牌和河牌。': 'Next hand after use, see the flop at the start but cannot see the turn or river.',
  '向全桌公布一条关于你底牌点数的假情报；不影响其他真实情报。': 'Announce false information about your hole-card ranks to the table without changing other true intel.',
  '开局私下得知其他玩家底牌里共有几张黑牌。': 'At the start of the hand, privately learn how many black hole cards other players hold in total.',
  '下一阶段开始时获得一项随机罕见千术，自身变为“登神阶梯II”。': 'At the next phase, gain a random rare trick and become Ascension Ladder II.',
  '下一阶段开始时获得一项随机史诗千术，自身变为“登神阶梯III”。': 'At the next phase, gain a random epic trick and become Ascension Ladder III.',
  '下一阶段开始时获得一项随机传说千术，自身变为“登神”。': 'At the next phase, gain a random legendary trick and become Ascended.',
  '每局开始向全桌公告：你已经登神。': 'At the start of each hand, announce to the table that you have ascended.',
  '移除已持有的全部千术，随机获得十项普通或罕见千术。': 'Lose all your tricks and gain ten random common or rare tricks.',
  '每阶段两次：被对手的主动千术作用时，打消对方这次使用（对方仍消耗次数），并在本局临时获得该千术。': 'Twice per phase, negate an opponent’s active trick targeting you (they still spend a use) and temporarily gain that trick for this hand.',
  '从八张随机牌中按顺序指定三张翻牌。': 'Choose the three flop cards, in order, from eight random cards.',
  '每局开局获得一张候选牌；翻前可换一张底牌，若没有使用，转牌时可改作河牌。': 'Get one candidate card each hand. Before the flop, swap it for a hole card; if unused, it may replace the river on the turn.',
});

Object.assign(EN, {
  '无需手动使用；自动生效': 'Automatic; no manual use needed',
  '每局限用一次': 'Once per hand', '每两局限用一次': 'Once every two hands',
  '每阶段限用 2 次': 'Twice per phase', '每阶段限用 1 次': 'Once per phase',
  '每阶段限用 3 次': 'Three times per phase',
  '整场限用 4 次': 'Four uses per match', '整场限用 6 次': 'Six uses per match',
  '整场限用 2 次': 'Two uses per match', '整场限用 1 次': 'One use per match',
  '整场限用 8 次': 'Eight uses per match', '整场限用 3 次': 'Three uses per match',
  '不限制次数': 'Unlimited uses', '每局限用 1 次': 'Once per hand',
  '整场最多使用复制的千术 2 次；未使用不计次': 'Use copied tricks at most twice per match; unused copies do not count',
  '每阶段限用 2 次，每局最多 1 次': 'Twice per phase, at most once per hand',
  '每阶段最多打消 2 次': 'Negate up to two uses per phase',
  '每局自动获得一张候选牌，可选用一次': 'Get one candidate card per hand; use it once',
  '整场剩余': 'Match uses left', '本阶段剩余': 'Phase uses left',
  '本局剩余': 'Hand uses left', '每两局可用：': 'Once every two hands: ',
  '（本局河牌替换不另扣）': ' (river replacement costs no extra use)',
  '（本局已用）': ' (already used this hand)', '被动生效': 'Passive effect',
  '不限次数': 'Unlimited uses',
  '每局发牌后，随机查看一名对手两张底牌的红黑。': 'After each deal, see the colors of both hole cards of one random opponent.',
  '每局发牌后，查看所有对手两张起始底牌的红黑。': 'After each deal, see the colors of both starting hole cards of every opponent.',
  '牌局中随时使用；获知未受防窥保护玩家的部分牌面信息。': 'Use any time during a hand to learn partial card information about players without peek protection.',
  '牌局中随时使用；指定一名未受防窥保护的对手。': 'Use any time during a hand; choose an opponent without peek protection.',
  '牌局中随时使用；指定未受防窥保护的对手及其一张底牌。': 'Use any time during a hand; choose an unprotected opponent and one of their hole cards.',
  '牌局中随时使用；查看所有未受防窥保护的对手。': 'Use any time during a hand; view all opponents without peek protection.',
  '每局发牌后触发。': 'Triggers after each deal.',
  '整场游戏持续生效。': 'Active throughout the match.',
  '持有期间持续生效。': 'Active while held.',
  '仅自己的行动回合且限翻前；从五张候选牌中选两张。': 'On your preflop turn only; choose two from five candidate cards.',
  '仅翻牌阶段自己的行动回合，指定转牌和河牌。': 'On your flop turn only; choose the turn and river.',
  '仅自己的行动回合；指定一名未全下、未受史诗防窥保护的对手。': 'On your turn only; choose an opponent who is not all in or protected by epic peek defense.',
  '每局结算前自动触发；底池至少有五个小盲。': 'Triggers before settlement if the pot has at least five small blinds.',
  '前三阶段自己的行动回合，随机抽取一位相邻玩家。': 'On your turn in the first three phases; targets a random adjacent player.',
  '河牌前自己的行动回合，抽取金额至少 10 筹码。': 'On your turn before the river; the amount taken must be at least 10 chips.',
  '仅翻牌前自己的行动回合；从前三张候选牌中选两张。': 'On your preflop turn only; choose two of the first three candidates.',
  '仅翻牌前自己的行动回合；从前四张候选牌中选两张。': 'On your preflop turn only; choose two of the first four candidates.',
  '翻前自选两张底牌；河牌回合可用备用牌换一张底牌。': 'Choose two hole cards preflop; on the river, swap a spare card for one hole card.',
  '首位玩家弃牌时触发。': 'Triggers when the first player folds.',
  '本局有玩家弃牌时自动私下获知其底牌。': 'Privately reveals hole cards when a player folds this hand.',
  '仅自己行动时；从已公开的弃牌中选一张替换底牌。': 'On your turn only; replace a hole card with one revealed folded card.',
  '牌局中随时查看未使用牌。': 'View unused cards any time during a hand.',
  '河牌阶段自己的行动回合；指定尚未行动的后位玩家，支付四分之一底池。': 'On your river turn; target a later-position player who has not acted and pay a quarter of the pot.',
  '仅自己的行动回合；公开自己的底牌，从筹码足够的对手收取大盲。': 'On your turn only; reveal your hole cards and collect a big blind from each opponent with enough chips.',
  '牌局中随时查看三张随机未使用牌。': 'View three random unused cards any time during a hand.',
  '首次有对手窥视或交换你的底牌时触发。': 'Triggers the first time an opponent peeks at or swaps your hole cards.',
  '仅河牌阶段自己的行动回合；令本局用千术换过公牌且未全下的玩家弃牌。': 'On your river turn only; make players who changed community cards this hand fold unless all in.',
  '有对手使用主动千术时触发（无声手法除外）。': 'Triggers when an opponent uses an active trick, except Silent Hands.',
  '牌局中随时使用；指定一名对手。': 'Use any time during a hand; choose an opponent.',
  '仅河牌阶段使用；最高牌型包含弃牌者。': 'Use on the river only; the highest hand category includes folded players.',
  '翻牌后使用；指定一名未受防窥保护的对手。': 'Use after the flop; choose an opponent without peek protection.',
  '仅自己的行动回合且在翻牌阶段；与当前最大牌型玩家交换底牌，对方已全下时不能使用。': 'On your flop turn only; exchange hole cards with a player in the highest hand category, unless they are all in.',
  '翻牌后自动私下获知转牌与河牌的红黑。': 'After the flop, privately learn the colors of the turn and river.',
  '河牌前使用；查看下一张公共牌点数是否达到 10。': 'Before the river, learn whether the next community card is 10 or higher.',
  '翻牌后、河牌前使用。': 'Use after the flop and before the river.',
  '翻前记录等于一个大盲的下注，翻牌后返还。': 'Records preflop bets equal to one big blind; refunds them after the flop.',
  '仅自己的行动回合且河牌前；猜河牌的花色，本局结束结算。': 'On your turn before the river; guess the river suit for settlement at hand end.',
  '仅自己的行动回合；选择自己的一张底牌替换。': 'On your turn only; choose one of your hole cards to replace.',
  '牌局中随时使用；指定一名已有千术的对手。': 'Use any time during a hand; choose an opponent who holds a trick.',
  '牌局中随时使用；只数尚未发出的牌，不含已翻出的公牌。': 'Use any time during a hand; count undealt cards only, excluding revealed community cards.',
  '河牌前使用；查看下一张公共牌。': 'Before the river, view the next community card.',
  '仅河牌阶段使用；只比较未弃牌且未受防窥保护的玩家。': 'Use on the river only; compare players who have not folded and lack peek protection.',
  '自己的行动回合使用；随机取得目标一项千术，替换偷师。': 'On your turn, gain one random trick from the target, replacing Steal a Trick.',
  '仅自己的行动回合；选择底牌，牌堆中须有同点数的不同花色牌。': 'On your turn only; choose a hole card. The deck must contain that rank in another suit.',
  '河牌前使用；查看下一张公共牌花色。': 'Before the river, see the suit of the next community card.',
  '翻牌后使用；比较未弃牌且未受防窥保护的对手。': 'Use after the flop; compare opponents who have not folded and lack peek protection.',
  '仅翻牌前自己的行动回合。': 'On your preflop turn only.',
  '仅自己的行动回合；指定未弃牌、未全下且未受史诗防窥保护的对手。': 'On your turn only; choose an opponent who has not folded, is not all in, and lacks epic peek defense.',
  '持有期间私下获知其他玩家的千术。': 'Privately know other players’ tricks while you hold this.',
  '选中时立即触发。': 'Triggers immediately when picked.',
  '自己的行动回合；只从可换牌的玩家中随机选目标，已全下的玩家除外。': 'On your turn; randomly target an eligible player who is not all in.',
  '仅翻牌前自己的行动回合；指定一名目标。': 'On your preflop turn only; choose a target.',
  '仅翻牌阶段自己的行动回合；与未揭晓的转牌和河牌交换。': 'On your flop turn only; exchange with the unrevealed turn and river.',
  '仅河牌阶段自己的行动回合；目标至少有二十个大盲。目标本局没用过主动千术时本次落空，仍消耗次数。': 'On your river turn only; target must have at least 20 big blinds. If they used no active trick this hand, this use is still spent.',
  '仅第三、四阶段可选；选中时立即触发。': 'Available only in phases three and four; triggers immediately when picked.',
  '自己的行动回合；至少三名未弃牌的玩家在局，且左右最近的两位未弃牌玩家都未全下、未受换牌保护。': 'On your turn; at least three players remain, and the nearest active players on both sides are not all in or swap protected.',
  '自己的行动回合；指定本局仍在场的对手。': 'On your turn; choose an opponent still in this hand.',
  '本局被主动千术作用时触发；复制品用掉后才计次数。': 'Triggers when an active trick affects you; counts only when the copied trick is used.',
  '选中时立即触发；不会获得自我暗示。': 'Triggers immediately when picked; cannot grant Self-Suggestion.',
  '自己的行动回合，从未使用牌中随机取 A 和 K 替换两张底牌。': 'On your turn, replace both hole cards with a random unused ace and king.',
  '自己的行动回合；已全下或受换牌保护的对手不受影响。': 'On your turn; all-in or swap-protected opponents are unaffected.',
  '自己的行动回合；牌堆须有可用的 A。': 'On your turn; an ace must be available in the deck.',
  '自己的行动回合；牌堆须有可用的 K。': 'On your turn; a king must be available in the deck.',
  '自己的行动回合；牌堆须有可用的 Q。': 'On your turn; a queen must be available in the deck.',
  '仅第一、二阶段可选；下一阶段选术时生效。': 'Available only in phases one and two; takes effect at the next trick pick.',
  '仅前三阶段可选；以后每次选术时生效。': 'Available only in the first three phases; applies to every future trick pick.',
  '每阶段首次被换牌千术作用时自动触发。': 'Triggers on the first card-swap trick affecting you each phase.',
  '每局发底牌时生效。': 'Applies when hole cards are dealt each hand.',
  '牌局中随时使用；跳过受防窥保护的玩家。': 'Use any time during a hand; skip players with peek protection.',
  '仅翻前或翻牌阶段自己的行动回合。': 'On your preflop or flop turn only.',
  '自己的行动回合指定一名下一局仍在场的对手。': 'On your turn, choose an opponent who will still be in the next hand.',
  '自己的行动回合发动，效果在下一局生效。': 'Use on your turn; takes effect next hand.',
  '翻牌后在自己的行动回合指定一名对手。': 'After the flop, choose an opponent on your turn.',
  '河牌单挑获胜时，按本局开局人数从落败者收取大盲。': 'When you win heads-up on the river, collect one big blind per starting player from the loser.',
  '每次以两对或更高牌型赢牌时获得随机普通千术。': 'Gain a random common trick whenever you win with two pair or better.',
  '别人对你取得的所有千术情报自动变为假信息。': 'All trick intel other players obtain about you becomes false.',
  '第一阶段不会出现；选中时立即触发。': 'Unavailable in phase one; triggers immediately when picked.',
  '底牌保护持有期间一直生效；锁定公共牌在转牌翻出前随时可用（不必轮到自己），每局一次。': 'Hole-card protection is always active while held. Lock one community card any time before the turn, even off turn, once per hand.',
  '河牌翻出前自己的行动回合，指定对手并猜两张底牌点数。': 'Before the river, on your turn, choose an opponent and guess both hole-card ranks.',
  '自己的行动回合；从可换的对手底牌中选点数最大的两张，只有分别高于自己对应底牌时才交换；已全下的对手不在其中。': 'On your turn, find the two highest-ranked swappable opponent hole cards and exchange each only if it outranks your matching card. All-in opponents are excluded.',
  '自己的行动回合，点选一张已翻出的公牌；已全下的玩家不受影响。': 'On your turn, choose a revealed community card. All-in players are unaffected.',
  '选中时，从每名其他玩家已持有的千术中随机获得一项。': 'When picked, gain one random trick already held by each other player.',
  '每局开局获知第五张公牌；局中看不到第三张公牌。': 'At each hand’s start, see the fifth community card; you cannot see the third during that hand.',
  '使用后下一局生效，开局获知转牌和河牌，但看不到前三张公牌；每局最多发动一次。': 'Next hand, see turn and river at the start but not the flop. Use at most once per hand.',
  '使用后下一局生效，开局获知前三张公牌，但看不到转牌和河牌；每局最多发动一次。': 'Next hand, see the flop at the start but not turn or river. Use at most once per hand.',
  '每局开局向全桌公布一条关于自己底牌点数的假情报。': 'At each hand’s start, announce false information about your hole-card ranks.',
  '每局开局私下获知对手底牌中的黑牌张数。': 'At each hand’s start, privately learn how many black hole cards opponents hold.',
  '仅第一阶段可选；下一阶段开始时触发。': 'Available only in phase one; triggers at the start of the next phase.',
  '仅第二阶段可选；下一阶段开始时触发。': 'Available only in phase two; triggers at the start of the next phase.',
  '仅第三阶段可选；下一阶段开始时触发。': 'Available only in phase three; triggers at the start of the next phase.',
  '每局开始向全桌公告已经登神。': 'At each hand’s start, announce to the table that you have ascended.',
  '仅第四阶段可选；选中时立即触发，不能由其他千术获得。': 'Available only in phase four; triggers immediately when picked and cannot be gained through other tricks.',
  '被对手的主动千术作用时自动触发（指定你为目标、换你的牌、收你的筹码等）。': 'Triggers when an opponent’s active trick affects you (targeting you, swapping your cards, taking your chips, etc.).',
  '仅翻牌前自己的行动回合；从八张随机牌中按顺序选三张翻牌。': 'On your preflop turn only; choose three flop cards in order from eight random cards.',
  '每局开局自动获得一张候选牌；替换操作只能在自己的行动回合完成。': 'Automatically get one candidate card each hand; replacements must be made on your turn.',
});

Object.assign(EN, {
  '你已被房主移出房间': 'The host removed you from the room',
  '无法恢复房间，请重新加入': 'Could not restore the room; please join again',
  '创建失败': 'Could not create the room', '加入失败': 'Could not join',
  '无法开始': 'Could not start', '连接已断开，请等待重连后操作': 'Connection lost; wait for reconnection',
  '尚未收到操作结果，请以牌桌最新状态为准': 'No action result yet; check the latest table state',
  '操作失败': 'Action failed', '踢出失败': 'Could not remove player',
  '已互相添加为好友': 'You are now friends', '好友申请已发送': 'Friend request sent',
  '好友申请发送失败': 'Could not send friend request', '添加机器人失败': 'Could not add bot',
  '未收到选术结果，请以最新房间状态为准': 'No trick-pick result yet; check the latest room state',
  '选术失败': 'Could not choose trick', '未收到刷新结果，请以最新候选为准': 'No refresh result yet; check the latest offers',
  '刷新失败': 'Refresh failed', '未收到千术结果，请以最新牌桌状态为准': 'No trick result yet; check the latest table state',
  '千术使用失败': 'Could not use trick', '看牌失败': 'Could not view cards',
  '公开失败': 'Could not reveal', '房间邀请': 'Room Invitation',
  '邀请你加入': 'invited you to join', '加入': 'Join',
  '横屏入座': 'Rotate to Play', '请旋转手机，或调宽浏览器窗口。': 'Rotate your phone or widen the browser window.',
  '正在恢复房间…': 'Restoring room…', '正在连接服务器…': 'Connecting to server…',
  '连接恢复中… 当前牌桌暂不可操作': 'Reconnecting… Table actions are temporarily unavailable',
  '请选择图片文件': 'Choose an image file', '图片读取失败': 'Could not read image',
  '无法读取这张图片': 'Could not open this image', '图片太大': 'Image is too large',
  '选择头像': 'Choose Avatar', '预设头像': 'Preset Avatar',
  '卡牌': 'Cards', '牌桌': 'Table', '持牌视角': 'POV Hands',
  '随机搭配': 'Randomize', '公告': 'News', '限时活动': 'Limited Events',
  '暂无进行中的活动': 'No events right now', '暂未开放': 'Coming soon',
  '在线玩家': 'Online Players', '申请': 'Requests', '房间中': 'In a Room',
  '好友列表读取失败': 'Could not load friends', '连接失败': 'Connection failed',
  '发送失败': 'Could not send', '已添加好友': 'Friend added', '已拒绝': 'Declined',
  '邀请已发送': 'Invitation sent', '邀请失败': 'Could not invite',
  '我的好友编号': 'My Friend Code', '编号已复制': 'Code copied',
  '请手动复制编号': 'Please copy the code manually', '好友编号': 'Friend Code',
  '输入好友编号': 'Enter friend code', '加好友': 'Add Friend',
  '还没有好友': 'No friends yet', '现在没有其他人在线': 'No other players online',
  '已是好友': 'Already Friends', '已申请': 'Requested',
  '同意申请': 'Accept Request', '同意': 'Accept', '拒绝': 'Decline',
  '没有待处理申请': 'No pending requests', '邀请': 'Invite', '复制': 'Copy',
  '关闭选择器': 'Close Picker', '个人页面': 'Profile',
  '资料': 'Info', '战绩': 'Record', '铭牌': 'Nameplate',
  '总对局数': 'Total Games', '最高得分': 'Best Score', '最近得分': 'Latest Score',
  '本周最大牌型': 'Best Hand This Week', '更换': 'Change',
  '个人介绍': 'Bio', '一句话介绍自己': 'Say something about yourself',
  '还没有填写昵称': 'No nickname yet', '正在读取记录…': 'Loading record…',
  '暂时无法读取记录': 'Record unavailable', '本周还没有记录': 'No records this week',
  '还没有对局记录': 'No game records yet', '按模式筛选': 'Filter by mode',
  '房间战绩': 'Room Results', '经典牌局（不限局数）': 'Classic Poker (unlimited)',
  '千术模式（16 局）': 'Trick Mode (16 hands)',
  '初始筹码至少需要': 'Starting chips must be at least',
  '千术情报': 'Trick Intel', '左': 'left', '右': 'right',
  '打开出千面板': 'Open Trick Panel', '已出局': 'Eliminated',
  '上一项': 'previous option', '下一项': 'next option',
  '关闭语音播报': 'Turn off voice announcements', '开启语音播报': 'Turn on voice announcements',
  '测试机器人：能过牌就过牌，遇到下注就弃牌；下一局入座': 'Test bot: checks if possible, folds to bets, joins next hand',
  '可在牌桌使用的换牌千术': 'Card-swap tricks usable at the table',
  '第一张': 'First', '第二张': 'Second', '第三张': 'Third',
  '控牌：按顺序选出转牌、河牌': 'Choose the turn, then the river',
  '定江山：按顺序选出三张翻牌': 'Choose the three flop cards in order',
  '留底／换底：在牌桌上选两张牌作为底牌': 'Choose two cards on the table as hole cards',
  '调包：先点击你要交换的底牌': 'First click the hole card you want to swap',
  '点击你要替换的那张底牌': 'Click the hole card to replace',
  '先选两个点数，再点击目标玩家的底牌确认猜测': 'Choose two ranks, then click the target’s hole card to confirm',
  '点击目标玩家的任一张底牌，指定作用对象': 'Click either target hole card',
  '点击目标玩家的一张底牌': 'Click a target hole card',
  '已选两张全换': 'Both Cards Selected', '切换为两张全换': 'Swap Both Cards',
  '选择千术候选牌': 'Choose Candidate Cards',
  '先选转牌，再选河牌': 'Choose the turn, then the river',
  '按翻开的顺序选三张翻牌': 'Choose three flop cards in reveal order',
  '选自己一张底牌，再选一张备用牌替换': 'Choose one hole card, then a spare card',
  '从候选牌中选择两张作为底牌': 'Choose two candidates as hole cards',
  '本局不计入局数，下一局仍是第': 'This hand does not count; the next is still hand',
  '四个阶段，每阶段选一次千术并进行四局': 'Four phases; pick a trick and play four hands in each',
  '阶段：选择千术': 'phase: Choose Trick', '刷新候选': 'Refresh offer',
  '换一张（剩': 'Replace card (', '次）': 'left)',
  '选中后升级为': 'Upgrades to', ' 项': ' items',
  '网络中断，语音已退出；连接恢复后请重新加入。': 'Connection lost; rejoin voice after reconnecting.',
  '无法访问麦克风，检查浏览器权限或是否为 HTTPS 访问': 'Microphone unavailable; check browser permissions or HTTPS',
  '在浏览器打开': 'Open in Browser',
  '好友服务连接超时': 'Friend service timed out',
  '经典绿': 'Classic Green',
});

Object.assign(EN, {
  '头像格式错误': 'Invalid avatar format', '头像格式无效或图片过大': 'Invalid avatar or image too large',
  '请求格式错误': 'Invalid request', '缺少请求回执': 'Request callback missing',
  '好友功能不可用': 'Friends are unavailable', '请先连接好友服务': 'Connect to the friend service first',
  '玩家不存在': 'Player not found', '机器人不能加好友': 'Bots cannot be added as friends',
  '对方暂时无法接收好友申请': 'This player cannot receive friend requests right now',
  '对方不是好友': 'This player is not your friend', '请先进入房间': 'Join a room first',
  '好友不在线': 'Friend is offline', '请先填写昵称': 'Enter a nickname first',
  '当前不在房间中': 'You are not in a room', '昵称格式错误': 'Invalid nickname',
  '请先离开当前房间': 'Leave your current room first',
  '房间号或昵称格式错误': 'Invalid room code or nickname', '房间不存在': 'Room not found',
  '这个名字已经在房间里了，换一个名字试试': 'That name is already in the room; try another',
  '游戏已经开始，无法加入': 'The game has started; you cannot join now',
  '房间已满': 'Room is full', '只有房主可以设置': 'Only the host can change settings',
  '游戏已开始': 'Game has started', '只有房主可以开始': 'Only the host can start',
  '游戏已经开始': 'Game has already started',
  '至少需要两位筹码足够的玩家': 'At least two players need enough chips',
  '游戏未进行': 'No game is in progress', '当前不在等待中': 'Not waiting for the next hand',
  '你将在下一局入座，无需确认本局': 'You will join next hand; no confirmation needed now',
  '只有房主可以添加机器人': 'Only the host can add bots',
  '现在不能添加机器人': 'Bots cannot be added now',
  '只有房主可以踢人': 'Only the host can remove players',
  '不能踢自己': 'You cannot remove yourself',
  '玩家已被移出房间': 'Player has been removed from the room',
  '消息不能为空': 'Message cannot be empty', '发得太快了': 'You are sending too quickly',
  '无效表情': 'Invalid emoji', '无效礼物': 'Invalid gift', '未知类型': 'Unknown type',
  '只有房主可以返回大厅': 'Only the host can return to the lobby',
  '只有房主可以操作': 'Only the host can do this',
  '只能在每局结束后的结算界面补筹码': 'Rebuy only on the results screen after a hand',
  '千术模式已完成最终结算': 'Trick Mode final results are complete',
  '该玩家已被移出房间': 'This player has been removed',
  '该玩家还在游戏中': 'This player is still in the game',
  '补充筹码必须至少够一个大盲': 'Rebuy must be at least one big blind',
  '牌堆没有符合纯粹主义者条件的牌': 'No deck card meets Purist conditions',
  '无效的加注金额': 'Invalid raise amount',
  '只能在摊牌阶段看牌': 'Cards can be viewed only at showdown',
  '不能看自己的牌': 'You cannot pay to view your own cards',
  '这名玩家的底牌已经公开了': 'This player’s hole cards are already public',
  '看不了这名玩家的牌': 'You cannot view this player’s cards',
  '筹码不够': 'Not enough chips', '已经看过了': 'Already viewed',
  '没有进行中的牌局': 'No hand is in progress',
  '只有弃牌的人可以公开自己的牌': 'Only a folded player can reveal their cards',
  '本局已有玩家全下，只能跟注、过牌或弃牌。': 'A player is all in; you may only call, check, or fold.',
  '没有其他可继续下注的玩家。': 'No other player can continue betting.',
  '本轮已加注一次，下一轮可再次加注。': 'You already raised this round; you may raise again next round.',
  '本局已有玩家全下，只能跟注、过牌或弃牌': 'A player is all in; you may only call, check, or fold',
  '当前不能执行此操作': 'This action is not available now',
  '牌桌与界面': 'Table and Interface',
  '牌桌铺满画面；手牌移到左下，操作区移到右下。': 'The table now fills the screen; hole cards sit at the lower left and actions at the lower right.',
  '四款手部贴图更新，袖口更宽。': 'Updated four hand illustrations with wider sleeves.',
  '新增好友申请与房间邀请。': 'Added friend requests and room invitations.',
  '设置新增音量、播报风格和皮肤选项。': 'Added volume, announcement style, and skin options.',
  '千术调整': 'Trick Updates',
  '登神只能由登神阶梯 III 获得。': 'Ascended can only be obtained through Ascension Ladder III.',
  '千术反转可响应作用于全场的主动千术。': 'Trick Reflection can respond to active tricks that affect the whole table.',
});

Object.assign(EN, {
  '当前不能刷新千术': 'Cannot refresh tricks now', '无效的候选栏位': 'Invalid offer slot',
  '该栏位已经刷新过': 'This slot has already been refreshed',
  '没有可刷新的千术': 'No trick available to refresh',
  '当前不能选千术': 'Cannot pick a trick now', '未知千术': 'Unknown trick',
  '千术不在候选中': 'This trick is not offered',
  '本阶段读秒已被其他玩家选走': 'Another player took this phase’s time trick',
  '留底已被其他玩家选走': 'Another player took this reserve trick',
  '盲注回声已被其他玩家选走': 'Another player took Blind Echo',
  '对手': 'Opponent', '留底': 'Reserve', '无人': 'Nobody', '暂无': 'None',
  '有': 'Yes', '没有': 'No', '红': 'Red', '黑': 'Black',
  '已全下玩家的底牌不能再被替换': 'All-in players’ hole cards cannot be replaced',
  '不动如山：目标的底牌不能被替换': 'Immovable: target hole cards cannot be replaced',
  '运筹帷幄：本局候选牌': 'Strategic Reserve: candidate card for this hand',
  '留底：翻前可选底牌': 'Reserve: hole cards to choose before the flop',
  '留底：后五张情报牌（河牌可换底牌）': 'Reserve: last five intel cards (one may replace a hole card on the river)',
  '留底：其余情报牌（本局不再使用）': 'Reserve: other intel cards (removed from this hand)',
  '押色命中：已向本局其他玩家收取大盲': 'Suit Bet hit: collected one big blind from each opponent',
  '押色未命中': 'Suit Bet missed',
  '本局已经使用过': 'Already used this hand', '每两局只能使用一次': 'Usable once every two hands',
  '本局使用次数已达上限': 'Hand use limit reached',
  '本阶段使用次数已达上限': 'Phase use limit reached',
  '整场使用次数已用完': 'Match use limit reached',
  '请先完成当前选牌': 'Finish the current card choice first',
  '本局没有留底候选牌': 'No reserve candidates this hand',
  '当前不能使用留底河牌替换': 'Cannot use the reserve river replacement now',
  '本局已经选过底牌': 'Hole cards already chosen this hand',
  '牌堆剩余牌不够': 'Not enough cards left in the deck',
  '候选牌已失效，请重新选择': 'Candidate cards changed; choose again',
  '当前不能使用此千术': 'This trick is unavailable now',
  '被动千术无需手动使用': 'Passive tricks do not need manual use',
  '本局千术已被禁用': 'Tricks are disabled for this hand',
  '本局自己的底牌被遮蔽，不能用千术查看': 'Your hole cards are hidden this hand and cannot be viewed with tricks',
  '摆份·不需要公牌：本局不能查看河牌': 'Bluff · No Board Needed: you cannot view the river this hand',
  '阴间千术：下一张公牌本局不可见': 'Underworld trick: the next community card is hidden this hand',
  '已弃牌，不能再锁定公共牌': 'You folded and cannot lock a community card',
  '只能在自己的行动回合使用行动千术': 'Action tricks can only be used on your turn',
  '只能在翻牌前选底牌': 'Choose hole cards before the flop',
  '当前不能使用留底': 'Reserve is unavailable now',
  '请选择本局的一名对手': 'Choose an opponent in this hand',
  '对方的底牌受到防窥保护': 'Opponent’s hole cards are peek protected',
  '只能在翻牌前、公共牌尚未被其他千术指定时使用': 'Use before the flop, while community cards are not set by another trick',
  '不动如山：转牌或河牌已被锁定，不能再指定': 'Immovable: turn or river is locked and cannot be chosen',
  '只能在翻牌阶段指定转牌和河牌': 'Choose the turn and river during the flop only',
  '牌局发生变化，请重新选择候选牌': 'Hand state changed; choose candidates again',
  '请从五张牌中选两张': 'Choose two of the five cards',
  '请选择自己一张底牌和一张备用牌': 'Choose one hole card and one spare card',
  '换底完成，新底牌已生效': 'Hole-card swap complete',
  '请按顺序选三张翻牌': 'Choose the three flop cards in order',
  '定江山：已指定三张翻牌': 'Control the Flop: three flop cards chosen',
  '请按转牌、河牌顺序选两张': 'Choose two cards in turn, then river order',
  '已指定转牌与河牌': 'Turn and river chosen',
  '牌堆中缺少可用的 A 或 K': 'No usable ace or king in the deck',
  '云中探花手：两张底牌已变为随机花色的 A 和 K': 'Ace-King from the Clouds: hole cards replaced with an ace and king of random suits',
  '本局候选牌已使用': 'Candidate card already used this hand',
  '运筹帷幄：候选牌已换入底牌': 'Strategic Reserve: candidate card replaced a hole card',
  '不动如山：河牌已被锁定，不能替换': 'Immovable: river is locked and cannot be replaced',
  '运筹帷幄：已将候选牌指定为河牌': 'Strategic Reserve: candidate card set as the river',
  '翻前请选择一张底牌，或在转牌阶段选择替换河牌': 'Choose a hole card preflop, or replace the river on the turn',
  '只能选择已公开的弃牌': 'Choose a revealed folded card',
  '请各选择一张牌': 'Choose one card from each group',
  '废牌·尽收：已从弃牌中换入一张底牌': 'Discard Exchange: folded card swapped into your hand',
  '没有可换牌的目标': 'No eligible swap target',
  '只能在翻牌前使用': 'Use before the flop only',
  '你中了特异功能·掩目，河牌前无法看到前三张公牌': 'Blindfolded: you cannot see the flop until the river',
  '只能在转牌前使用': 'Use before the turn only',
  '摆份·不需要公牌：本局河牌将对你隐藏，赢牌时收取弃牌者筹码': 'Bluff · No Board Needed: the river is hidden; collect from folded players if you win',
  '本场已没有下一局': 'No next hand remains in this match',
  '你中了摆份·跟你盲开：下局看不到自己的底牌': 'Bluff · Blind Together affects you: your hole cards will be hidden next hand',
  '摆份·无需看牌：下局看不到底牌，河牌高牌不弃牌可获额外奖励': 'Bluff · No Look: your hole cards are hidden next hand; reaching the river with high card can earn a bonus',
  '只能在翻牌后盖住仍在局玩家的底牌': 'Hide an active player’s hole cards only after the flop',
  '你中了特异功能·意念闭塞：本局结束前看不到自己的底牌': 'Mental Block affects you: your hole cards stay hidden this hand',
  '只能在翻牌阶段使用': 'Use on the flop only',
  '不动如山：转牌或河牌已被锁定，不能交换': 'Immovable: turn or river is locked and cannot be exchanged',
  '探囊取物：两张底牌与未公开的转牌、河牌交换完成': 'Steal Future Board: exchanged hole cards with unrevealed turn and river',
  '只能在河牌阶段使用': 'Use on the river only',
  '目标筹码不足二十个大盲': 'Target has fewer than 20 big blinds',
  '至少需要三名未弃牌的玩家': 'At least three players must remain',
  '相邻玩家的牌受到保护': 'Neighboring players’ cards are protected',
  '相邻玩家已全下，底牌不能再被替换': 'A neighboring player is all in; their hole cards cannot be replaced',
  '左邻右舍：相邻玩家各一张牌已交换': 'Neighbors: exchanged one card from each neighbor',
  '你中了功力耗尽，本局千术不能再发动': 'Trick Shutdown affects you: you cannot use tricks this hand',
  '没有可以替换底牌的玩家': 'No player has swappable hole cards',
  '精神错乱：其他玩家底牌已随机替换': 'Mind Scramble: other players’ hole cards have been randomized',
  '第四阶段不能使用': 'Unavailable in phase four',
  '相邻玩家筹码不足': 'Neighbor has insufficient chips',
  '河牌阶段不能截流': 'Pot Drain cannot be used on the river',
  '底池筹码不足': 'Not enough chips in the pot',
  '对方已全下，底牌不能再被替换': 'Opponent is all in; hole cards cannot be replaced',
  '对方的底牌不能被转移': 'Opponent’s hole cards cannot be moved',
  '不动如山：对方的底牌不能被替换': 'Immovable: opponent’s hole cards cannot be replaced',
  '请选择双方各一张牌': 'Choose one hole card from each player',
  '不能指定已弃牌或全下的玩家': 'Cannot target a folded or all-in player',
  '只能指定尚未行动且排在你之后的玩家': 'Target must act after you and have not acted yet',
  '该玩家已经中了买断效果': 'This player is already affected by Paid Fold',
  '支付筹码不足': 'Not enough chips to pay',
  '支付后筹码不足以完成本次跟注，无法使用': 'Using this would leave too few chips to call',
  '没有筹码足够的对手': 'No opponent has enough chips',
  '对方还没有弃牌': 'Opponent has not folded',
  '没有尚未揭晓的公共牌': 'No unrevealed community card remains',
  '翻牌后才能使用': 'Use after the flop',
  '没有可比较的玩家': 'No eligible player to compare',
  '对方还没有千术': 'Opponent holds no tricks',
  '对方没有可偷学的千术': 'Opponent has no trick to steal',
  '河牌后不能押色': 'Suit Bet cannot be used after the river',
  '本局已经押过河牌花色': 'River suit already guessed this hand',
  '请选择河牌花色': 'Choose the river suit',
  '只能在河牌阶段验牌': 'Board Audit can only be used on the river',
  '没有可处理的换公牌玩家': 'No eligible community-card swapper',
  '你被“我要验牌”查出换公牌，本局已弃牌': 'Board Audit caught your community-card swap; you folded',
  '请选择自己的一张底牌': 'Choose one of your hole cards',
  '牌堆里没有符合条件的牌': 'No matching card in the deck',
  '不动如山：转牌或河牌已被锁定，不能倒序': 'Immovable: a locked turn or river prevents Reverse Board',
  '牌堆不足以倒序发牌': 'Not enough cards in the deck for Reverse Board',
  '倒序：本局五张公共牌将按相反顺序依次翻出': 'Reverse Board: five community cards will be revealed in reverse order',
  '对方底牌不能被交换': 'Opponent’s hole cards cannot be exchanged',
  '请选择对方的一张底牌': 'Choose one opponent hole card',
  '牌堆不足': 'Not enough cards in the deck',
  '没有可查看的玩家': 'No player available to view',
  '请选择左牌或右牌': 'Choose the left or right hole card',
  '没有可窥视的对手': 'No opponent can be peeked at',
  '仅河牌阶段使用': 'Use on the river only',
  '低于两对': 'below two pair', '不是': 'not', '不会': 'will not',
  '点数相连': 'consecutive ranks', '点数不相连': 'nonconsecutive ranks',
  '不同花': 'different suits',
  '只能比较仍在局的玩家': 'Compare only players still in this hand',
  '领先': 'ahead', '落后': 'behind',
  '没有可交换的最强玩家（已全下的玩家不能交换）': 'No strongest-hand player available for exchange; all-in players are excluded',
  '只能在转牌翻出前锁定': 'Lock before the turn is revealed',
  '请选择锁定转牌还是河牌': 'Choose to lock the turn or river',
  '只能在河牌前猜仍可行动的对手': 'Before the river, guess an opponent who can still act',
  '请选择两张牌的点数': 'Choose the ranks of both cards',
  '你中了管中窥豹：下一次行动只能弃牌': 'Guess the Hole Cards affects you: your next action must be fold',
  '没有两张可交换的对手底牌': 'Fewer than two opponent hole cards can be exchanged',
  '最大的两张对手底牌都没有高于你的对应底牌': 'Neither of the two highest opponent cards outranks your matching card',
  '请选择一张已翻出的公共牌': 'Choose a revealed community card',
  '其他玩家没有同点数底牌': 'No other player holds a matching-rank hole card',
  '牌堆没有足够的新牌': 'Not enough new cards in the deck',
  '千术尚未实现': 'Trick is not implemented',
});

Object.assign(EN, {
  '：额外获得 ': ': Also gained ', '：暂时没有可获得的千术': ': No tricks available to gain',
  ' 的千术抵抗抵消了本次换牌；次数照常消耗': ' negated this swap with Trick Resistance; the use still counts',
  '千术抵抗：已抵消 ': 'Trick Resistance: Negated ', ' 的换牌千术': '’s card-swap trick',
  '第六感：': 'Sixth Sense: ', ' 对你使用了 ': ' used against you: ',
  '千术反转：本局暂时获得 ': 'Trick Reflection: Temporarily gained ',
  '，使用后才计次数': '; a use counts only if used',
  '首位弃牌者 ': 'First player to fold: ', ' 的弃牌': '’s folded cards',
  ' 已经登神了': ' has ascended', '公开情报：': 'Public intel: ',
  ' 的一张底牌点数为 ': ' has a hole card with rank ',
  '：预知公牌（后续千术可能改动）': ': Foreseen community cards (later tricks may change them)',
  '口袋对子人数：': 'Players with pocket pairs: ',
  ' 的起始底牌红黑：': '’s starting hole-card colors: ',
  '红潮：对手底牌共有 ': 'Red Tide: Opponents have ',
  '黑潮：对手底牌共有 ': 'Black Tide: Opponents have ',
  ' 张红牌': ' red cards', ' 张黑牌': ' black cards',
  ' 位对手握有 J、Q 或 K': ' opponents hold a J, Q, or K',
  ' 的千术：': '’s tricks: ',
  '盲注回声：收回 ': 'Blind Echo: Reclaimed ',
  '抽筹·探囊：从底池抽走 ': 'Pot Pickpocket: Took ',
  '：从 ': ': Took ', ' 获得 ': ' gained ',
  '：向 ': ': Paid ', ' 支付 ': ' paid ',
  '翻牌前其他人全部弃牌，本局不计入局数，下一局仍是第 ': 'Everyone else folded preflop; this hand does not count. The next hand is still #',
  '牌仙子：获得 ': 'Card Fairy: Gained ',
  '无冤无仇：': 'Random Replacement: ',
  ' 的一张底牌已随机更换': ' had one hole card randomly replaced',
  '摆份·跟你盲开：下局你和 ': 'Bluff · Blind Together: Next hand, you and ',
  ' 都看不到自己的底牌': ' cannot see your hole cards',
  '捉千：': 'Catch a Cheat: ',
  ' 本局没有使用主动千术，本次落空（次数照常消耗）': ' used no active trick this hand; this attempt fails and still costs a use',
  '：从底池抽走 ': ': Took ', '从底池抽走 ': 'Took ',
  '抽筹·顺手：从 ': 'Neighbor Pickpocket: Took ',
  ' 取得 ': '’s chips: ', '已与 ': 'Swapped cards with ', ' 换牌': ' swapped cards',
  ' 与你换了底牌': ' swapped hole cards with you',
  '已支付 ': 'Paid ', ' 筹码给 ': ' chips to ',
  '；你完成本次行动后，目标轮到行动时只能弃牌': '; after your action, the target must fold on their next turn',
  '你中了赠筹·买断：': 'Paid Fold affects you: ',
  ' 支付你 ': ' paid you ',
  '；轮到你行动时只能弃牌': '; you must fold on your next turn',
  '公开底牌，获得 ': 'Revealed hole cards and gained ',
  '未使用牌：': 'Unused cards: ', '：受防窥保护': ': Peek protected',
  '下一张公共牌是': 'The next community card is ',
  '下一张公共牌的花色：': 'Next community-card suit: ',
  '下一张公共牌': 'Next community card',
  '自照：': 'Future Self: ', '算牌：牌堆中还剩 ': 'Card Count: Deck still has ',
  ' 当前牌型：': '’s current hand: ',
  '抬眼：': 'Table Leader: ', ' 持有当前最高牌型之一': ' has one of the highest hand categories',
  '当前有 ': 'There are ', ' 位未受防窥保护的对手强于你': ' unprotected opponents stronger than you',
  ' 的一项千术：': '’s random trick: ',
  '偷师：永久获得 ': 'Steal a Trick: Permanently gained ',
  '已押河牌花色为': 'Guessed river suit: ', '：下一局生效': ': Takes effect next hand',
  ' 已弃牌': ' folded', '：新底牌已生效': ': New hole cards are active',
  '牌堆里没有可用的 ': 'No usable ', '：较小的底牌已替换': ': Lower hole card replaced',
  '偷梁入手：已与 ': 'Steal a Hole Card: Swapped with ',
  ' 与你交换了一张底牌': ' exchanged one hole card with you',
  '第一张翻牌花色：': 'First flop-card suit: ',
  ' 的两张底牌': '’s two hole cards', ' 已选千术：': '’s chosen tricks: ',
  '河牌公报：当前最高牌型 ': 'River Report: Highest hand category is ',
  '河牌公报：本局最高牌型': 'River Report: Highest hand category is ',
  '胜负直觉：你当前': 'Winning Instinct: You are currently ',
  '天命易手：已与 ': 'Fate Swap: Exchanged with ',
  ' 交换两张底牌': ' exchanged both hole cards',
  ' 与你交换了两张底牌': ' exchanged both hole cards with you',
  '不动如山：已锁定': 'Immovable: Locked ',
  '管中窥豹：猜中 ': 'Guess the Hole Cards: Correctly guessed ',
  '，其下次行动只能弃牌': '; they must fold on their next turn',
  '管中窥豹：未猜中 ': 'Guess the Hole Cards: Incorrect guess for ',
  '终极替换：已换入 ': 'Ultimate Swap: Swapped in ',
  ' 张更大的对手底牌': ' stronger opponent hole cards',
  '禁止成对：已替换其他玩家点数为 ': 'No Pairs: Replaced opponent hole cards of rank ',
  ' 的底牌': ' hole cards',
  ' 的终极抵抗反转打消了你的 ': ' negated your ',
  '（次数照常消耗）': ' (the use still counts)',
  '终极抵抗反转：打消了 ': 'Ultimate Counter: Negated ',
  '，本局暂时获得该千术': '; temporarily gained that trick this hand',
  '破局录：': 'Trick Trace: ', ' 使用了 ': ' used ',
  '捉千：从 ': 'Catch a Cheat: Collected from ', ' 收取 ': ': ',
  ' 的 ': '’s ',
});

Object.assign(EN, {
  '玩家': 'Player', '好友编号无效': 'Invalid friend code',
  '已经是好友': 'Already friends', '申请已发送': 'Request sent',
  '对方申请过多': 'This player has too many pending requests',
  '申请不存在': 'Request not found',
  '只会过牌，遇到下注就弃牌': 'Checks if possible and folds to bets',
  '送礼物': 'Send Gift', '移出房间': 'Remove from Room',
  '你中了管中窥豹：轮到你行动时只能弃牌。': 'Guess the Hole Cards affects you: you must fold on your next turn.',
  '你中了赠筹·买断：轮到你行动时只能弃牌。': 'Paid Fold affects you: you must fold on your next turn.',
  ' 次': ' uses',
  ' 张牌': ' cards',
});

const entries = Object.entries(EN).sort((a, b) => b[0].length - a[0].length);

const fragments = [
  ['等待 ', 'Waiting for '], [' 行动', ' to act'], ['房间 ', 'Room '],
  ['第 ', 'Hand '], [' 局', ' hands'], [' 人在线', ' online'], [' 人', ' players'],
  [' 筹码', ' chips'], ['已确认', 'Ready'], ['秒后', ' seconds until '],
  ['（借用）', ' (Borrowed)'], ['（全下）', ' (All In)'],
];

export function translate(source) {
  const trimmed = source.trim();
  if (!trimmed || !/[\u3400-\u9fff]/u.test(trimmed)) return source;
  if (EN[trimmed]) return source.replace(trimmed, EN[trimmed]);
  const dynamic = [
    [/^机器人(\d+)$/, (_, number) => `Bot ${number}`],
    [/^(.+)的操作$/, (_, name) => `${name}’s actions`],
    [/^送礼物给 (.+)$/, (_, name) => `Send a gift to ${name}`],
    [/^选择你自己的(左|右)张底牌$/, (_, side) => `Choose your ${side === '左' ? 'left' : 'right'} hole card`],
    [/^选择(.+)的(左|右)张底牌$/, (_, name, side) => `Choose ${name}’s ${side === '左' ? 'left' : 'right'} hole card`],
    [/^调包：已选你的(左|右)牌，再点击对手的一张底牌$/, (_, side) => `Swap: Your ${side === '左' ? 'left' : 'right'} card is selected; click an opponent hole card`],
    [/^查看 (.+) 的底牌，花费 (\d+) 筹码$/, (_, name, chips) => `View ${name}’s hole cards for ${chips} chips`],
    [/^给 (.+) 补至 (\d+) 筹码$/, (_, name, chips) => `Rebuy ${name} to ${chips} chips`],
    [/^(.+)的收听音量$/, (_, name) => `${name}’s listening volume`],
    [/^(.+) 的底牌$/, (_, name) => `${name}’s hole cards`],
    [/^第 (\d+(?:\/\d+)?) 局$/, (_, count) => `Hand ${count}`],
    [/^第 (\d+) 张$/, (_, count) => `Card ${count}`],
    [/^本局不计入局数，下一局仍是第 (\d+) 局$/, (_, count) => `This hand doesn’t count; the next hand is still Hand ${count}`],
    [/^(\d+) 人在线 · (.+)$/, (_, count, rest) => `${count} online · ${translate(rest)}`],
    [/^牌桌语音，(\d+) 人在线$/, (_, count) => `Table voice, ${count} online`],
    [/^第 (\d+) 阶段：选择千术$/, (_, phase) => `Phase ${phase}: Choose a Trick`],
    [/^换一张（剩 (\d+) 次）$/, (_, count) => `Replace Card (${count} left)`],
    [/^已出局（(\d+)）$/, (_, chips) => `Eliminated (${chips})`],
    [/^本局净(赢|输) (\d+)$/, (_, result, chips) => `Net ${result === '赢' ? '+' : '-'}${chips}`],
    [/^标准德州，共 (\d+) 局$/, (_, count) => `Standard Hold’em, ${count} hands`],
    [/^(\d+)月(\d+)日(?: (.*))?$/, (_, month, day, rest) =>
      `${new Intl.DateTimeFormat('en-US', { month: 'short' }).format(new Date(2026, Number(month) - 1, 1))} ${day}${rest ? ` ${rest}` : ''}`],
    [/^筹码不足以加注到 (\d+)。$/, (_, amount) => `Not enough chips to raise to ${amount}.`],
    [/^单轮下注上限为 (\d+)，无法继续加注。$/, (_, amount) => `Round bet cap is ${amount}; cannot raise further.`],
    [/^整局下注上限为 (\d+)，无法继续加注。$/, (_, amount) => `Hand bet cap is ${amount}; cannot raise further.`],
    [/^受其他玩家筹码限制，无法加注到 (\d+)。$/, (_, amount) => `Other players’ chips limit this raise; cannot raise to ${amount}.`],
    [/^加注不能超过其他玩家能跟上的额度（(\d+)）$/, (_, amount) => `Raise cannot exceed what other players can call (${amount})`],
    [/^初始筹码不能低于一个大盲（(\d+)）$/, (_, amount) => `Starting chips must be at least one big blind (${amount})`],
    [/^至少需要 (\d+) 人$/, (_, count) => `At least ${count} players required`],
    [/^最多 (\d+) 人$/, (_, count) => `At most ${count} players allowed`],
    [/^下一张公共牌是(红|黑)牌$/, (_, color) => `The next community card is ${color === '红' ? 'red' : 'black'}.`],
    [/^(.+) 的(左|右)张底牌点数：(.+)$/, (_, name, side, rank) => `${name}’s ${side === '左' ? 'left' : 'right'} hole-card rank: ${rank}`],
    [/^(.+) 的(左|右)牌$/, (_, name, side) => `${name}’s ${side === '左' ? 'left' : 'right'} card`],
    [/^终极抵抗反转：打消了 (.+) 的 (.+)，本局暂时获得该千术$/, (_, player, trick) =>
      `Ultimate Counter: Negated ${player}’s ${translate(trick)} and gained it for this hand`],
  ];
  for (const [pattern, format] of dynamic) {
    const match = trimmed.match(pattern);
    if (match) return source.replace(trimmed, format(...match));
  }
  let result = source;
  for (const [zh, en] of entries) {
    result = result.replaceAll(zh, en);
  }
  for (const [zh, en] of fragments) result = result.replaceAll(zh, en);
  return result;
}

const textOrigins = new WeakMap();
const attributeOrigins = new WeakMap();
const attributes = ['aria-label', 'title', 'placeholder', 'alt'];

export function localizePage(language) {
  const root = document.body;
  document.documentElement.lang = language === 'en' ? 'en' : 'zh-CN';

  function visit(node) {
    if (node.nodeType === Node.TEXT_NODE) {
      const parent = node.parentElement;
      const botName = /^机器人\d+$/.test((textOrigins.get(node)?.original || node.nodeValue).trim());
      if (parent?.closest('.room-chat-line, .avatar')) return;
      if (!botName && parent?.closest('.seat-name-text, .friend-item strong, .title-identity-copy small')) return;
      if (!botName && (parent?.matches('.player-list-name, .settlement-player, .settlement-peek-viewed, .voice-member-name strong')
        || (parent?.matches('.title-identity-copy strong') &&
          (textOrigins.get(node)?.original || node.nodeValue).trim() !== '未填写昵称')
        || (parent?.matches('.friend-invite strong') && node === parent.firstChild))) return;
      const previous = textOrigins.get(node);
      const original = previous && node.nodeValue === previous.last ? previous.original : node.nodeValue;
      const next = language === 'en' ? translate(original) : original;
      textOrigins.set(node, { original, last: next });
      if (node.nodeValue !== next) node.nodeValue = next;
      return;
    }
    if (node.nodeType !== Node.ELEMENT_NODE || node.matches('script, style, textarea')) return;
    const saved = attributeOrigins.get(node) || {};
    for (const attribute of attributes) {
      if (!node.hasAttribute(attribute)) continue;
      const current = node.getAttribute(attribute);
      const previous = saved[attribute];
      const original = previous && current === previous.last ? previous.original : current;
      const next = language === 'en' ? translate(original) : original;
      saved[attribute] = { original, last: next };
      if (current !== next) node.setAttribute(attribute, next);
    }
    attributeOrigins.set(node, saved);
    for (const child of node.childNodes) visit(child);
  }

  visit(root);
  // Chinese is the source text: one pass restores anything an English session changed, and new
  // content is already Chinese, so there is nothing to watch.
  if (language !== 'en') return () => {};
  const observer = new MutationObserver((changes) => {
    for (const change of changes) {
      if (change.type === 'characterData') visit(change.target);
      else if (change.type === 'attributes') visit(change.target);
      else for (const node of change.addedNodes) visit(node);
    }
  });
  observer.observe(root, { subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: attributes });
  return () => observer.disconnect();
}
